### ISSUE TITLE
Certificate Errors from gh

### ISSUE THREAD

**Issue by goodwillcoding** [jingweno/gh#232]
When I run gh against a local GHE instance I get this. 
https://<ghe instance>/api/v3/authorizations: x509: certificate signed by unknown authority

- All the certs on the machine running gh are ok
- Same URL works with wget and curl

**Comment by jingweno** [comment]
This should be fixed in latest release of https://github.com/github/hub/releases/tag/v2.2.0-rc1. Note that [`gh` will be known as GitHub CLI](https://github.com/github/hub/issues/475). Closing.

**Comment by juancampa** [comment]
Hey @jingweno this is still happening for me in v2.2.0-rc1 when I try to ```hub --pull-request``` to a corporate Github
